version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3406:3306"
  #  rubocop:
  #    build: .
  #    command: bundle exec rubocop
  #  test-unit:
  #    build: .
  test-rails:
    build:
      context: .
      dockerfile: Dockerfile-rails
      args:
        - RUBY_VERSION=3.1.3
        - RAILS_VERSION=6.1
    volumes:
      - ./dummy_app/rails/:/app/tmp/dummy/
    depends_on:
      - mysql
