version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  postgres:
    image: "postgres:16"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
  mockserver:
    image: kennethreitz/httpbin
    ports:
      - "8080:80"
  #  rubocop:
  #    build: .
  #    command: bundle exec rubocop
  #  test-unit:
  #    build: .
  test-rails:
    build:
      context: .
      dockerfile: Dockerfile-rails
      args:
        - RUBY_VERSION=3.1.3
        - RAILS_VERSION=6.1
    volumes:
      - ./dummy_app/rails/:/app/tmp/dummy/
    depends_on:
      - mysql
