[package]
name = "rack_analyzer"
version = "0.1.0"
edition = "2021"
authors = ["Takahiro Ebato <ebato.takahiro@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.4" }
sqlparser = { version = "0.34.0", features = ["visitor"] }
