inherit_gem:
  syntax_tree: config/rubocop.yml

AllCops:
  TargetRubyVersion: 3.0.2
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false

Layout/LineLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
Naming/FileName:
  Enabled: true
  Exclude:
    - 'lib/rack-dev-insight.rb'

Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: true
  Max: 50
Metrics/AbcSize:
  Enabled: true
  Max: 30
Metrics/ParameterLists:
  Enabled: true
  Max: 10
