version: '3'
services:
  ruby:
    build:
      context: .
      args:
        - RUBY_VERSION=${RUBY_VERSION:-3.0.2}
    tty: true
    volumes:
      - ./:/app/
      - ../openapi/:/openapi/
    depends_on:
      - mysql
      - postgresql
      - mock-http-server

  mysql:
    image: mysql:${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  postgresql:
    image: postgres:${POSTGRES_VERSION:-16}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
  mock-http-server:
    image: kennethreitz/httpbin
    ports:
      - "8080:80"

  dummy-app-rails:
    build:
      context: .
      args:
        - RUBY_VERSION=${RUBY_VERSION:-3.0.2}
    volumes:
      - ./tmp/dummy_app/rails/:/app/
      - ./:/gem/
    command: "/bin/bash -c 'rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b 0.0.0.0'"
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    depends_on:
      - mysql
      - postgresql
      - mock-http-server
