# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

gem 'appraisal'
gem 'committee', '~> 5.0'
gem 'dotenv', '~> 2.8'
gem 'mysql2', '~> 0.5.5'
gem 'pg', '~> 1.5.4'
gem 'rack-test'
gem 'rake', '~> 13.0'
gem 'rake-compiler'
gem 'rspec', '~> 3.0'
gem 'rspec-parameterized', '~> 1.0'
gem 'rubocop', '~> 1.21'
gem 'simplecov', '~> 0.18'
gem 'sqlite3', '~> 1.5.4'
gem 'syntax_tree'
