# frozen_string_literal: true

require 'bundler/gem_tasks'
require_relative 'tasks/dummy_app/rails'

require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec)

require 'rubocop/rake_task'
RuboCop::RakeTask.new

require 'syntax_tree/rake_tasks'
STREE_CONFIG = ->(t) do
  t.source_files = FileList[%w[Gemfile Rakefile lib/**/*.rb spec/**/*.rb tasks/**/*.rb]]
  t.print_width = 120
  t.plugins = [%w[plugin/single_quotes plugin/trailing_comma plugin/disable_auto_ternary]]
end
SyntaxTree::Rake::CheckTask.new(&STREE_CONFIG)
SyntaxTree::Rake::WriteTask.new(&STREE_CONFIG)

task default: :spec
task fix: %i[rubocop:autocorrect_all stree:write]
