name: Publish gem

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: publish gem
        if: startsWith(github.ref, 'refs/tags/v')
        working-directory: gem/
        env:
          GEM_API_KEY: ${{secrets.GEM_API_KEY}}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_API_KEY}\n" > $HOME/.gem/credentials
          gem build rack-dev_insight.gemspec
          for i in *.gem; do
            if [ -f "$i" ]
            then
              gem push "$i" || true
            fi
          done
