name: Main

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install redoc-cli
        run: npm install @redocly/cli -g
      - name: Check OpenAPI
        run: cd openapi && redocly lint openapi.yaml
      - name: Up docker
        run: cd gem && docker compose up -d ruby
      - name: bundle install
        run: cd gem && docker compose exec ruby /bin/bash -c 'bundle install'
      - name: Check rubocop
        run: cd gem && docker compose exec ruby /bin/bash -c 'bundle exec rake rubocop'
      - name: Check syntax tree
        run: cd gem && docker compose exec ruby /bin/bash -c 'bundle exec rake stree:check'
  test-ruby:
    runs-on: ubuntu-latest
    name: Ruby-${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.0.2'
          - '3.1.4'
          - '3.2.2'
          - '3.3.0'
    steps:
      - uses: actions/checkout@v4
      - name: Up docker
        run: cd gem && RUBY_VERSION=${{ matrix.ruby }} docker compose up -d ruby
      - name: Run Tests
        run: cd gem && docker compose exec ruby /bin/bash -c 'bundle install && bundle exec appraisal install && bundle exec appraisal rake spec'
