name: Main

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: rubocop & stree
    steps:
      - uses: actions/checkout@v3
      - name: Checkout And Build
        run: cd gem && docker compose up -d ruby-rust
      - name: Run rubocop
        run: cd gem && docker compose exec ruby-rust /bin/bash -c 'bundle install && bundle exec rake rubocop'
      - name: Run syntax tree check
        run: cd gem && docker compose exec ruby-rust /bin/bash -c 'bundle install && bundle exec rake stree:check'
  test-ruby:
    runs-on: ubuntu-latest
    name: Ruby-${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.0.2'
          - '3.1.4'
          - '3.2.2'
    steps:
      - uses: actions/checkout@v3
      - name: Checkout And Build
        run: cd gem && RUBY_VERSION=${{ matrix.ruby }} docker compose up -d ruby-rust
      - name: Run Tests
        run: cd gem && docker compose exec ruby-rust /bin/bash -c 'bundle install && bundle exec rake compile && bundle exec appraisal install && bundle exec appraisal rake spec'
  test-rust:
    runs-on: ubuntu-latest
    name: Rust
    steps:
      - uses: actions/checkout@v3
      - name: Checkout And Build
        run: cd gem && docker compose up -d ruby-rust
      - name: Run Tests
        run: cd gem && docker compose exec ruby-rust /bin/bash -c 'cargo test --all'
